### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by mahmoud-eskandari** [akveo/blur-admin#52] opened 2016-06-02 19:29 UTC
When I Running 'gulp' CMD Command In Root Folder 
And gulp running good and creating release folder and .tmp folder...

But Project not compiling good And index.html not created in release folder!

How to fix This Problem?

**Comment by AllyW** [comment] 2016-06-08 06:11
I can't fine the index.html either

**Comment by lugovsky** [comment] 2016-06-10 17:30
@mahmoud-eskandari @AllyW I don't experience this issue guys. Maybe some access control issues on your side? Please check if you have write permissions to the project directory. 

IF access control is not the issue, it would be very helpful if you provided some debug info

**Comment by vazh** [comment] 2016-06-13 15:56
@AllyW try updating your npm first `npm i -g npm`.
then delete any `bower_components` & `node_modules` that existed.
then try installing it again with `npm install`

**Comment by AllyW** [comment] 2016-06-28 09:38
Thanks, it works perfect now.

**Comment by nnixaa** [comment] 2016-07-29 13:52
Hey guys, as the issue is resolved I'm closing it now, let us know if you have any questions.

**Closed by nnixaa** 2016-07-29 13:52 UTC

**Comment by pzuk** [comment] 2016-08-16 06:57
thanks, it works! :+1:
